volumes:
  wordpress:
    name: wordpress-volume
    driver: local
    driver_opts:
      device: /home/ciusca/data/wordpress-data
      o: bind
      type: none
  mariadb:
    name: mariadb-volume
    driver: local
    driver_opts:
      device: /home/ciusca/data/mariadb-data
      o: bind
      type: none

networks:
  inception-net:
    name: inception-net
    driver: bridge

services:

  nginx:
    depends_on:
      wordpress:
        condition: service_started

    container_name: nginx
    build: ./requirments/nginx
    image: nginx-image
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception-net
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirments/wordpress
    image: wordpress-image
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception-net
    ports:
      - "9000:9000"
    expose:
      - "9000"
    restart: always

  mariadb:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: mariadb
    build: ./requirments/mariadb
    image: mariadb-image
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception-net
    restart: always